# Generated by Django 5.1.4 on 2024-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome do produto', models.CharField(max_length=20)),
                ('Descrição do produto', models.CharField(max_length=20)),
                ('Preço do produto', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
