# Generated by Django 5.1.4 on 2024-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Preço do produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='Preço',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Descrição do produto',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='Nome do produto',
            field=models.CharField(max_length=100),
        ),
    ]
