# Generated by Django 5.1.4 on 2024-12-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_produto_preço_do_produto_produto_preço_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Descrição do produto',
            new_name='Descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Nome do produto',
            new_name='Nome',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='Preço',
            new_name='Preco',
        ),
    ]
